### ISSUE TITLE
Release 0.6.3

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#166]
Would be nice to do a small patch release if that is ok. Also added a PR to update Cython while we are at it. ( https://github.com/zarr-developers/numcodecs/pull/165 )

**Comment by alimanfoo** [comment]
SGTM. @jakirkham would you like to merge #165 then make the release?

**Comment by jakirkham** [comment]
SGTM. AFAIK I don't have permissions on PyPI.

**Comment by alimanfoo** [comment]
On Thu, 31 Jan 2019, 08:01 jakirkham <notifications@github.com wrote:

> SGTM. AFAIK I don't have permissions on PyPI.
>
Should be sorted now.

**Comment by jakirkham** [comment]
Thanks for doing that.

Have merged that PR and made a release to PyPI. PR ( https://github.com/conda-forge/numcodecs-feedstock/pull/36 ) will update the conda-forge package once merged.

**Comment by jakirkham** [comment]
Now published on conda-forge as well :)
