### ISSUE TITLE
blosc not included in numcodecs' pip package (neither on zarr)

### ISSUE THREAD

**Issue by dangpzanco** [zarr-developers/numcodecs#183]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
from numcodecs import blosc
```
or
```python
from zarr import blosc
```

#### Problem description

When trying to make `zarr` work in a multi-threaded environment, I tried following the guide at [`zarr`'s docs](https://zarr.readthedocs.io/en/stable/tutorial.html#configuring-blosc), but every time I tried importing `blosc` this error message showed up:
`ImportError: cannot import name 'blosc'`

I also noticed `'blosc'` is not included in `dir(numcodecs)`.

#### Version and installation information

* Value of ``numcodecs.__version__``: `0.6.3`
* Version of Python interpreter: `Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]`
* Operating system: `Windows-10-10.0.17763-SP0`
* How NumCodecs was installed: using pip (no virtualenv), when installing `zarr`

#### Temporary Fix

After reading the bug report template (when writing this issue), I realized I could try installing `zarr` (and consequently `numcodecs`) via `conda`. It works! So the problem is with the pip package (maybe only on Windows?)...

**Comment by alimanfoo** [comment]
Hi @dangpzanco, when installing via pip, an attempt will be made to build the C extensions from sources, which includes the numcodecs.blosc module. If the compilation fails for any reason, the installation will be retried without the C extensions. This will mean that the numcodecs package is installed, but the numcodecs.blosc module is not. If you run pip with `-v` you should see some messages in the logging to this effect. If you're on Windows you would need to have a C compiler installed to build the C extensions.

**Comment by llllllllll** [comment]
This is likely caused by compilation failures on newer gcc/clang building c-blosc. Are you seeing compilation errors that reference `_xgetbv`? If so, I have opened a PR to update c-blosc to the latest release which fixes this compilation issue (at least for me locally).

**Comment by alimanfoo** [comment]
Yes the blosc module will be missing if compilation of the extension failed for some reason, pip installs from source and compiles extensions. Running `pip uninstall numcodecs` then `pip install -v --no-cache-dir numcodecs` should give some more verbose logging including any compilation failures.

Installing via conda should work as the extensions are pre-compiled.

**Comment by sofroniewn** [comment]
Just to add in case anyone else is facing this too - I needed to run
`pip install -v --no-cache-dir numcodecs`
after I messed around with some numcodecs stuff to trigger the regeneration of the C extensions.

**Comment by jakirkham** [comment]
Going to go ahead and close as this appears to be answered. Though please let us know if you have any other questions. 🙂
