### ISSUE TITLE
Zstd not present after pip install on Mac/Windows

### ISSUE THREAD

**Issue by jeromekelleher** [zarr-developers/numcodecs#191]
On the current version of the PyPI package it seems there's a problem with building Zstd on Mac and Windows, which I found from two downstream users [here](https://github.com/tskit-dev/tsinfer/issues/161).

I don't have a windows or Mac machine, so I can't reproduce, but I thought I'd raise the issue. Can someone with a Mac try a pip install please and see if Zstd builds OK?

**Comment by alimanfoo** [comment]
Hi @jeromekelleher, if Zstd (or Blosc or LZ4) is not present then that means that building of cython extensions failed during pip install, because pip compiles extensions from sources (we don't distribute pre-built wheels).

If this is happening on windows or mac, it may be because there is no compiler installed. 

We have windows (appveyor) CI but not osx CI currently. Would be great if someone with a mac with a compiler could verify that numcodec currently installs from pip.

**Comment by jeromekelleher** [comment]
It would be good to get to the bottom of this all right - @hyanwong, would you mind trying an install of numcodecs on your mac using pip please?

**Comment by hyanwong** [comment]
Minor permissions issues on my laptop, which is almost certainly a problem with my personal setup rather than a generic thing, but numcodecs still installs fine:

```
Yans-MacBook-Air:tsinfer-hyanwong yan$ pip3 install numcodecs
Collecting numcodecs
  Downloading https://files.pythonhosted.org/packages/6f/1c/b1537659c5900312f77454f3eca25c728bf1b0ab24ccbcca5e1d712a661b/numcodecs-0.6.3.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 1.2MB/s 
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.7/site-packages (from numcodecs) (1.15.4)
Building wheels for collected packages: numcodecs
  Building wheel for numcodecs failed: [Errno 13] Permission denied: '/Users/yan/Library/Caches/pip/wheels/75'
Failed to build numcodecs
Installing collected packages: numcodecs
  Running setup.py install for numcodecs ... done
Successfully installed numcodecs-0.6.3
```

**Comment by alimanfoo** [comment]
@hyanwong can you also try:

```
from numcodecs import Zstd
```

...to confirm the extension modules are present?

**Comment by hyanwong** [comment]
> from numcodecs import Zstd

Works fine on my system.

I wonder whether we are assuming cython is installed, and the people whoe reported problems didn't have it. But I can't see how it would then install fine when doing a `pip install numcodecs` from scratch (ISTR that installing numcodecs on its own is fine, but it doesn't work when installed as part of the zarr installation process - correct me if I am wrong @jeromekelleher )

**Comment by jeromekelleher** [comment]
> But I can't see how it would then install fine when doing a pip install numcodecs from scratch (ISTR that installing numcodecs on its own is fine, but it doesn't work when installed as part of the zarr installation process - correct me if I am wrong @jeromekelleher )

I think the issue we're hitting is that people are installing ``tsinfer`` using pip (as we don't have a conda package yet), and numcodecs isn't building properly for whatever reason. It can't be because there's no compiler though, because tskit/tsinfer would certainly fail if that were the case.

Perhaps it is the Cython dep as Yan suggests?

**Comment by jeromekelleher** [comment]
That must be it I think: Cython is a soft background requirement (see [here](https://github.com/zarr-developers/numcodecs/blob/master/setup.py#L319)), so installation succeeds when it's not present.

I'm not sure this is the right default these days - most of the codecs we'll actually want need to be compiled, so perhaps cython should be added as an ``install_requires`` package?

**Comment by alimanfoo** [comment]
Cython is not required, we distributed the cythonized C sources and those will be used if Cython is not present on the system.

**Comment by jeromekelleher** [comment]
> Cython is not required, we distributed the cythonized C sources and those will be used if Cython is not present on the system.

Aha, I see. Hmm, must be something else happening then - as I say, the compiler must be present or install should have failed entirely.

**Comment by alimanfoo** [comment]
Numcodecs appears to [build fine and tests pass on osx](https://travis-ci.org/zarr-developers/numcodecs/jobs/559932828) (with system Python 2.7).

If you can ask one of the users experiencing the problem to run `pip install -v numcodecs` then you should get some logging that says if compiling extensions failed and may give some clues as to why.

I'm sure you'll be thinking this too but definitely recommend getting tsinfer onto conda-forge if possible :-)

**Comment by hyanwong** [comment]
It's not a problem when installing numcodecs using pip directly (that works). It's only when installing it as part of another package (in this case tsinfer). @marianne-aspbury can replicate this by uninstalling numcodecs and tsinfer, then `pip install`ing tsinfer on its own, which triggers a numcodecs installation. She can post the `pip install -v` output from that in this thread.

**Comment by marianne-aspbury** [comment]
output of `pip install numcodecs -v`
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\mazmysta\AppData\Local\Temp\pip-ephem-wheel-cache-m2vrhz5r
Created temporary directory: C:\Users\mazmysta\AppData\Local\Temp\pip-req-tracker-cfze76wb
Created requirements tracker 'C:\\Users\\mazmysta\\AppData\\Local\\Temp\\pip-req-tracker-cfze76wb'
Created temporary directory: C:\Users\mazmysta\AppData\Local\Temp\pip-install-eyuxoyfb
Collecting numcodecs
  1 location(s) to search for versions of numcodecs:
  * https://pypi.org/simple/numcodecs/
  Getting page https://pypi.org/simple/numcodecs/
  Looking up "https://pypi.org/simple/numcodecs/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/numcodecs/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/numcodecs/
    Found link https://files.pythonhosted.org/packages/8b/02/1d198dbe82f6a8782f3030c0bb8dc2c73960ad4f728efe810192a1c0442a/numcodecs-0.0.0.tar.gz#sha256=91e9564aa77e10e0d603523ffc5b0fe0761d8170ef5c55ea72d8b6b4fcdcaea5 (from https://pypi.org/simple/numcodecs/), version: 0.0.0
    Found link https://files.pythonhosted.org/packages/b9/e9/a87b8c24283e6aff810b9760d2f789fcdfb436827e7269176d196502b543/numcodecs-0.0.1.tar.gz#sha256=5b2095bfec7771be7ea66c27534db8bddef1848ed34d09b7dd28228e952d5076 (from https://pypi.org/simple/numcodecs/), version: 0.0.1
    Found link https://files.pythonhosted.org/packages/45/ff/a17e492bd47e2907868f65515111237aa2b722bb71604855450f034f3a96/numcodecs-0.1.0.tar.gz#sha256=d2bf40baaa94bb137519faa09e9e3d3d0c92f994759bb3222907eaa2680ee9c9 (from https://pypi.org/simple/numcodecs/), version: 0.1.0
    Found link https://files.pythonhosted.org/packages/f2/81/740bf4fcfa5cb526d22cf455e5ed69f56bad259c995f6c489baa2b6bdad3/numcodecs-0.1.1.tar.gz#sha256=d79ea83d816c42eb87dffeb9a337c897410db481e4118319f5306a1ef9189708 (from https://pypi.org/simple/numcodecs/), version: 0.1.1
    Found link https://files.pythonhosted.org/packages/1c/24/1335fa29e71f289b40c93f2daed9652e3ac1fc8317fa8d3a40826f54551b/numcodecs-0.2.0.tar.gz#sha256=6926e9d30a6fb99930476d897043608e4e299258a16b043b18c4cd344bec7a21 (from https://pypi.org/simple/numcodecs/), version: 0.2.0
    Found link https://files.pythonhosted.org/packages/04/43/a9c26c77f1d5ffbae6a6e8b566b82ed7e3ebeb473601fab07794d3027cd6/numcodecs-0.2.1.tar.gz#sha256=25dfdb1ed28c9426f86712c9746e891ca8a6d41928fb3737d2fc951daed1cb51 (from https://pypi.org/simple/numcodecs/), version: 0.2.1
    Found link https://files.pythonhosted.org/packages/3b/bd/a6c860304a35d3c82b38dcb4a40896a70380633ed8f380816a0674c0e63f/numcodecs-0.3.0.tar.gz#sha256=f0c41daeb45f081f6f17073ef41a89b0eed5bb7c830eba74a5209364ac5bdc65 (from https://pypi.org/simple/numcodecs/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/cd/ed/d7b15625301832b25996547c39f26039b495e27d4194805eb70f853a11fd/numcodecs-0.3.1.tar.gz#sha256=5694aa3307de57166b6c1c3b7f437af1a1b54867804b90739527dacf7a361e87 (from https://pypi.org/simple/numcodecs/), version: 0.3.1
    Found link https://files.pythonhosted.org/packages/5c/e9/ca88634afd88f959d3e764bc20f3f997b10878cd78ca5774ac0f157a6b85/numcodecs-0.4.0.tar.gz#sha256=2fa711722d16b89dbfe395c2aa21770994e6955c23af23c4d8536a6b61ac16e1 (from https://pypi.org/simple/numcodecs/), version: 0.4.0
    Found link https://files.pythonhosted.org/packages/d8/22/f836056a4e2344961715ee74ccf117b18fd166cad93dcfad6dd2b6a9ae1a/numcodecs-0.4.1.tar.gz#sha256=2673056d7e110e7737b6d2ead878356b7ca3aa27e98ed2c31d311b128c70927f (from https://pypi.org/simple/numcodecs/), version: 0.4.1
    Found link https://files.pythonhosted.org/packages/36/3e/000562d22a1e3bfc25e2a9a292917fa8189cbc709bd8988430ea42cdd5df/numcodecs-0.5.0.tar.gz#sha256=46123681a5ba49d634d62c26d8c4efcd1e9d7c54e410d07e6a27ffe9597dcb60 (from https://pypi.org/simple/numcodecs/), version: 0.5.0
    Found link https://files.pythonhosted.org/packages/24/3f/6a00fd2ac6874cc763529d4ae0d6d321669093f1e63c1bafe087e7f47ea4/numcodecs-0.5.1.tar.gz#sha256=99ccbd3894188ece3c001f5935f4411f5ce91957271377bd44c38aa03e9a5db0 (from https://pypi.org/simple/numcodecs/), version: 0.5.1
    Found link https://files.pythonhosted.org/packages/04/d0/7afe32763cc38d758c6cad6bed90fa1515c39cc5f2ed4b7e18ee15b485a6/numcodecs-0.5.2.tar.gz#sha256=4c71d09ea34196f6f5a0e2091a7f41a7a5964a0bb4cbcbec8b92049c8799b417 (from https://pypi.org/simple/numcodecs/), version: 0.5.2
    Found link https://files.pythonhosted.org/packages/07/68/80b36ea5214218e825044008bca1bb82421b8cd2e814143e0e5d5e949861/numcodecs-0.5.3.tar.gz#sha256=6f62f9225919b2cc951c7fe7fdeb616e46ebeda4623481602218df0759814acf (from https://pypi.org/simple/numcodecs/), version: 0.5.3
    Found link https://files.pythonhosted.org/packages/e4/1c/bfbfbea45cc3af571f5e5ee09e81f2141430bbc50ef8f3c75e3abf807dba/numcodecs-0.5.4.tar.gz#sha256=8579e9ea11fba76844e83fa873c1935546caf640ecad4e72b42395f93e7fdee4 (from https://pypi.org/simple/numcodecs/), version: 0.5.4
    Found link https://files.pythonhosted.org/packages/e2/a1/d95c9a6d11169bc51a133900e8142708795a46b9972a25ec77bd56a12b56/numcodecs-0.5.5.tar.gz#sha256=7fdb60c40e902933f2ca4f65c8489d56697e7b0e4dffac4cb48ac58d8cce3aad (from https://pypi.org/simple/numcodecs/), version: 0.5.5
    Found link https://files.pythonhosted.org/packages/2b/37/55f6a4884803846f66e03dc4272e2a1ccace9c174a239965883a89946157/numcodecs-0.6.0.tar.gz#sha256=7144d293627d6317a4ac17836693117f52f74ff997fcd9eb2348b78ede359866 (from https://pypi.org/simple/numcodecs/), version: 0.6.0
    Found link https://files.pythonhosted.org/packages/16/82/f846d562a10ed4da26c3ab801afac9e72d7431aaa98cf2312311c5d8db42/numcodecs-0.6.1.tar.gz#sha256=9fa9a0216e6e5fd0eb95a178dc7fedcaa595fe94aee3fb2bd3f807859b8758af (from https://pypi.org/simple/numcodecs/), version: 0.6.1
    Found link https://files.pythonhosted.org/packages/a9/15/83019d8dea8ec2d303b4209ed179f78b5033513445f0f5f2cf9fde3b353b/numcodecs-0.6.2.tar.gz#sha256=c7ffa57bd8c9776eef12afab0e6fda843cda277d4bb55bcf0d048b5e38bc71e1 (from https://pypi.org/simple/numcodecs/), version: 0.6.2
    Found link https://files.pythonhosted.org/packages/6f/1c/b1537659c5900312f77454f3eca25c728bf1b0ab24ccbcca5e1d712a661b/numcodecs-0.6.3.tar.gz#sha256=5e98413d5d1156def888acd131bed7f3c21313847521efbd7f3707103de5d820 (from https://pypi.org/simple/numcodecs/), version: 0.6.3
  Using version 0.6.3 (newest of versions: 0.0.0, 0.0.1, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6.0, 0.6.1, 0.6.2, 0.6.3)
  Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  Using cached wheel link: file:///C:/Users/mazmysta/AppData/Local/pip/Cache/wheels/75/ea/37/8a1c2b6e937606f90dd0a9659783790d922efd1cf98d7a82a9/numcodecs-0.6.3-cp37-none-any.whl
  Added numcodecs from file:///C:/Users/mazmysta/AppData/Local/pip/Cache/wheels/75/ea/37/8a1c2b6e937606f90dd0a9659783790d922efd1cf98d7a82a9/numcodecs-0.6.3-cp37-none-any.whl to build tracker 'C:\\Users\\mazmysta\\AppData\\Local\\Temp\\pip-req-tracker-cfze76wb'
  Removed numcodecs from file:///C:/Users/mazmysta/AppData/Local/pip/Cache/wheels/75/ea/37/8a1c2b6e937606f90dd0a9659783790d922efd1cf98d7a82a9/numcodecs-0.6.3-cp37-none-any.whl from build tracker 'C:\\Users\\mazmysta\\AppData\\Local\\Temp\\pip-req-tracker-cfze76wb'
Requirement already satisfied: numpy>=1.7 in c:\users\mazmysta\anaconda3\lib\site-packages (from numcodecs) (1.16.2)
Installing collected packages: numcodecs

Successfully installed numcodecs-0.6.3
Cleaning up...
Removed build tracker 'C:\\Users\\mazmysta\\AppData\\Local\\Temp\\pip-req-tracker-cfze76wb'

**Comment by alimanfoo** [comment]
Hi @marianne-aspbury, can you run `pip install -v --no-cache-dir numcodecs` to force building from source (log output above shows pip is installing a cached wheel from a previous build).

**Comment by marianne-aspbury** [comment]
Okay, I ran the command above. Here's a text file of the output since it's very long.
[numcodecs_install.txt](https://github.com/zarr-developers/numcodecs/files/3402029/numcodecs_install.txt)

**Comment by alimanfoo** [comment]
Thanks @marianne-aspbury, the log shows all C extensions being built successfully on your windows system, so the `numcodecs.Zstd` class should be available. Can you double-check that running `python -c 'from numcodecs import Zstd'` generates an error?

**Comment by alimanfoo** [comment]
@marianne-aspbury thanks just saw your edit.

**Comment by alimanfoo** [comment]
@marianne-aspbury I would guess that, for some reason, a previous installation of numcodecs failed to build the C extensions, but then a wheel (without extensions) was cached and was reused for all subsequent installation attempts. When you did `pip install -v --no-cache-dir numcodecs` that forced a fresh installation from source, which succeeded to build C extensions this time round.

**Comment by hyanwong** [comment]
Right - glad we solved this. I wonder if in the tsinfer installation pathway, the numcodecs extension is being installed too early, and so e.g. users without Cython are installing numcodecs, then Cython.

It could be, of course, that they tried to install numcodecs for some other reason beforehand, which was installed without Zstd support, and re-installing just uses the cached version.

**Comment by jeromekelleher** [comment]
Hmm, looks like this was an unlikely combination of two different errors then on OSX and Windows. Closing the issue as it seems there isn't a problem. Sorry for the noise @alimanfoo!

**Comment by alimanfoo** [comment]
> Right - glad we solved this. I wonder if in the tsinfer installation pathway, the numcodecs extension is being installed too early, and so e.g. users without Cython are installing numcodecs, then Cython. Strange that it works on AppVeyor in that case.

Cython is not required at all to build extensions, so this couldn't be the reason. 

> It could be, of course, that they tried to install numcodecs for some other reason beforehand, which was installed without Zstd support, and re-installing just uses the cached version.

Yes, e.g., if an attempt was made to install numcodecs before a compiler was installed, that would result in a cached wheel missing built C extensions. I'm sure there's lot's of other fun reasons why this could have happened :-)

**Comment by alimanfoo** [comment]
> Hmm, looks like this was an unlikely combination of two different errors then on OSX and Windows. Closing the issue as it seems there isn't a problem. Sorry for the noise @alimanfoo!

No worries, feel free to reopen if problems recur :-)
