### ISSUE TITLE
User experience around failed compilation

### ISSUE THREAD

**Issue by llllllllll** [zarr-developers/numcodecs#196]
This is related to https://github.com/zarr-developers/numcodecs/pull/195, but when running setup.py, why does the code explicitly catch compilation failures and proceed without C extensions (https://github.com/zarr-developers/numcodecs/blob/master/setup.py#L364-L369).

`pip` doesn't print any of the stderr/stdout of a setup.py unless the whole process fails, so the error messages don't get logged when the C extensions don't get built. This leads import/attribute errors in `zarr` and `numcodecs` at runtime after what appears to be a successful install.

I understand that the C extensions may not work in all environments, and users may want to be able to install `numcodecs` without the C backed codecs. Would the zarr developers be interested in any of the following:

- Add a custom attribute/import error to the `numcodecs` module when the C extensions haven't been built.
- Explicitly opt-out of C extensions with an environment variable like: `NUMCODECS_NO_EXTENSION_MODULES=1`
- Automatically exclude extensions modules in known environments where they don't work, like maybe pypy.

**Comment by jeromekelleher** [comment]
I've been caught out by this behaviour also - I'd have thought it was better to fail noisily and not install at all if C extensions can't be compiled (it's the commonly used codecs that fail, right?). People on platforms where compilation is tricky will probably be using conda anyway.

**Comment by llllllllll** [comment]
Yeah, in my case it was blosc that was failing to compile, but my code was only attempting to use the `vlen` codecs which would likely have worked.

**Comment by alimanfoo** [comment]
I would be very happy for the behaviour to change so installation fails if
compiling any C extensions fails.

**Comment by jakirkham** [comment]
Do you want to send a PR, @llllllllll?

**Comment by llllllllll** [comment]
PR open here: https://github.com/zarr-developers/numcodecs/pull/197
