### ISSUE TITLE
Dropping `LegacyMsgPack`

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#217]
We ran into some issues with `LegacyMsgPack` and `msgpack-python` 1.0.0+ recently. In particular they came up in an attempt update the `numcodecs` feedstock ( https://github.com/conda-forge/numcodecs-feedstock/pull/48 ). Though presumably they exist in the wild as well. This raises the question of when do we want to drop `LegacyMsgPack`. Thoughts?

cc @jrbourbeau

**Comment by alimanfoo** [comment]
I'd favour dropping `LegacyMsgPack`, I'd guess there was relatively little use in the wild, we deprecated it pretty early on.

**Comment by jrbourbeau** [comment]
I agree, dropping is my preference as well. It's been deprecated for over a year (4 releases over that time period)
