### ISSUE TITLE
Drop LegacyJSON codec

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/numcodecs#225]
We recently dropped the LegacyMsgPack codec (#218). The LegacyJSON codec was deprecated around the same time, I think we could remove it now too.

**Comment by jakirkham** [comment]
Agreed. That would be good to drop 🙂

**Comment by joshmoore** [comment]
Somehow I missed that this dropped support for the codec ID and not just an implementation. We might want to think about getting numcodecs to 1.0 so that we can clearly mark such bumps with a major version change.

**Comment by jakirkham** [comment]
In SemVer, with `0.x` releases each increase in `x` can break the API (hence dropping here is allowed). This happened in 0.7.0.

We left the keys alone as both `json` and `json2` are still valid. One would just need an older version of Numcodecs to read the former.

Interestingly the two JSON implementations are a good example of the codec versioning question raised in spec issue ( https://github.com/zarr-developers/zarr-specs/issues/148 ).
