### ISSUE TITLE
Add link to docs on github page

### ISSUE THREAD

**Issue by mrocklin** [zarr-developers/numcodecs#255]
This repository comes up as the first hit in google for a search for "numcodecs".  The docs are clearly available in the README, but it might be slightly more convenient (and help with SEO) if we also placed the link on the github page.

**Comment by jrbourbeau** [comment]
There's this link to the docs on the right side of the GitHub repo:

<img width="738" alt="Screen Shot 2020-09-23 at 9 11 10 PM" src="https://user-images.githubusercontent.com/11656932/94092868-74f67800-fde1-11ea-8a02-95c30f74bae2.png">

Is that what you're proposing, or something else?

**Comment by jakirkham** [comment]
Yeah it’s weird that GitHub moves “about” off to the side like that. Second time that has confused someone today.

I’m guessing Matt would like to optimize things so Google can find the docs. Typical this seems fine. That said, I know NumFOCUS raised a concern regarding Google services and GDPR compliance recently. For this reason we turned off various Google services in conda-forge. So am a little wary of turning these things on here (unless someone wants to do the legwork to make sure we would be legally compliant).

**Comment by mrocklin** [comment]
Ah!  Sorry, this is just my mistake then.  Thanks for the explanation gents.
