### ISSUE TITLE
Drop/replace `array_decode_utf8` from `benchmark_vlen.ipynb`

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#319]
In PR ( https://github.com/dask/fastparquet/pull/580 ) included in `fastparquet` release `0.6.0`, `array_decode_utf8` was dropped from `fastparquet.speedups`. We should either drop or replace [this benchmark from `notebook/benchmark_vlen.ipynb`]( https://github.com/zarr-developers/numcodecs/blame/15f17138b9b41e99faa4a2670e2580a782547d6b/notebooks/benchmark_vlen.ipynb#L45-L67 ).

For context this notebook was originally added in PR ( https://github.com/zarr-developers/numcodecs/pull/56 ).

**Comment by jakirkham** [comment]
cc @martindurant (in case you have any thoughts here; no worries if not 🙂)

**Comment by martindurant** [comment]
I had no idea that this existed!

**Comment by jakirkham** [comment]
The function or the benchmark? In either case think it was totally reasonable to drop that code from `fastparquet` (it looked kind of like an internal function). Just didn't know if there was something else we should be using here or if we should just drop it.

**Comment by martindurant** [comment]
The encode part was rolled into pack_byte_array, so note reachable from outside, definitely an internal thing.
