### ISSUE TITLE
Failed to install numcodecs on Py39 + Windows 10

### ISSUE THREAD

**Issue by JacksonMaxfield** [zarr-developers/numcodecs#325]
Moving over an issue reported to napari-aicsimageio when it is a numcodecs bug: https://github.com/AllenCellModeling/napari-aicsimageio/issues/47

@PanosOik can you please fill out the missing information in this GitHub issue.

#### Problem description

Explain why the current behavior is a problem, what the expected output/behaviour 
is, and why the expected output/behaviour is a better solution.

Failed to install numcodecs with pip on Py39 and Windows 10

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__``
* Version of Python interpreter: Python 3.9
* Operating system (Linux/Windows/Mac): Windows
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda") pip in a conda environment

Also, if you think it might be relevant, please provide the output from ``pip list`` or
``conda list`` depending on which was used to install NumCodecs.

**Comment by JacksonMaxfield** [comment]
You should be able to see which version of numcodecs was attempting to be installed in the pip install log. That would be very helpful.

**Comment by PanosOik** [comment]
The version was numcodecs-0.9.1

**Comment by JacksonMaxfield** [comment]
I think this is now resolved -- waiting on confirmation it was an env / pip caching issue.
