### ISSUE TITLE
Coverage badge status Unknown.

### ISSUE THREAD

**Issue by Alt-Shivam** [zarr-developers/numcodecs#331]
The coverage badge shows the status `Unknown`.
I want to work on this, If this is valid.
Thanks 😃 

![image](https://user-images.githubusercontent.com/81817735/176211194-6cbd2acb-b84f-4126-a8a3-b9fdac68125e.png)

**Comment by joshmoore** [comment]
Use of coveralls needs to be replaced with codecov (https://app.codecov.io/gh/zarr-developers/numcodecs) as was done in https://github.com/zarr-developers/zarr-python/commit/f7125bb2dfb1982f452f72b01071a3f50a1200df etc.

**Comment by Alt-Shivam** [comment]
Got it. @joshmoore 
will generate a PR soon...

**Comment by dstansby** [comment]
Looks like this is fixed now: https://github.com/zarr-developers/numcodecs?tab=readme-ov-file#numcodecs
