### ISSUE TITLE
Ubuntu releases and `ci-linux.yaml`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [zarr-developers/numcodecs#340]
#### Problem description

Perhaps add Ubuntu 22.04 to CI?
https://github.com/zarr-developers/numcodecs/blob/244c9d018bd4fedf01ffe174e2eae97b1ce64ce6/.github/workflows/ci-linux.yaml#L12

Or use `ubuntu-latest` instead? Here are supported runners, but I'm not certain the documentation is up-to-date:
[Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

**Comment by joshmoore** [comment]
No objections to trying 22.04 out as long as the builds don't get too long.

**Comment by DimitriPapadopoulos** [comment]
Perhaps building for 18.04 and 22.04 instead of 18.04 and 22.04 would be a good compromise?

**Comment by joshmoore** [comment]
Also a good option. Anyone else have thoughts?

**Comment by joshmoore** [comment]
Let's go for oldest and newest, then @DimitriPapadopoulos.

**Comment by DimitriPapadopoulos** [comment]
* `ubuntu-18.04` has been dropped in https://github.com/zarr-developers/numcodecs/pull/351, see [GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/).
* `ubuntu-20.04` could be changed to `ubuntu-latest`: `ubuntu-latest` currently points to `ubuntu-20.04` but I suppose it will switch to `ubuntu-22.04` at some point, see [Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).

**Comment by joshmoore** [comment]
If we don't have a pressing reason for multiple, maybe let's just go with "latest" at this point.
