### ISSUE TITLE
'bitround' codec not registered

### ISSUE THREAD

**Issue by miccoli** [zarr-developers/numcodecs#346]
#### Minimal, reproducible code sample

```python
import numcodecs

codec = numcodecs.get_codec({"id": "bitround", "keepbits": 16})
```
fails with `ValueError: codec not available: 'bitround'` while

```python
import numcodecs
from numcodecs.bitround import BitRound

numcodecs.register_codec(BitRound, codec_id="bitround")

codec = numcodecs.get_codec({"id": "bitround", "keepbits": 16})
```
is ok.

#### Problem description

`BitRound` is not yet properly registered: not sure if this is by pourpose or a minor glitch....

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__``: `0.10.1`
* Version of Python interpreter: 3.10.4
* Operating system (Linux/Windows/Mac): Linux/Mac
* How NumCodecs was installed: "using pip into virtual environment"
*

**Comment by joshmoore** [comment]
Thanks, @miccoli. Please see #347

```
In [4]: numcodecs.get_codec({"id": "bitround", "keepbits":1})
Out[4]: BitRound(keepbits=1)
```

**Comment by miccoli** [comment]
Thanks @joshmoore for the quick fix.
