### ISSUE TITLE
Move to pyproject.toml

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#364]
It would be good to move to `pyproject.toml` in Numcodecs. In particular it would be nice to add build requirements (like Cython) and [`setup_requires`]( https://github.com/zarr-developers/numcodecs/blob/a3e05fd36f2cd7a2c903c4d5d9f787961a7a5905/setup.py#L335-L338 ) to `pyproject.toml`.

This should also allow us to do things like dropped the vendored C files, which cause us some pain periodically ( https://github.com/zarr-developers/numcodecs/pull/358#issuecomment-1281371763 ). Plus drop some of [the complexity in `setup.py`]( https://github.com/zarr-developers/numcodecs/blob/a3e05fd36f2cd7a2c903c4d5d9f787961a7a5905/setup.py#L10-L15 ).

FWIW this was done for Zarr in PR ( https://github.com/zarr-developers/zarr-python/pull/1158 ).

**Comment by jakirkham** [comment]
cc @Saransh-cpp @joshmoore

**Comment by jakirkham** [comment]
Yep that's definitely true. Even an incremental move or moving most things over would be a welcome improvement 🙂

**Comment by joshmoore** [comment]
Thanks, @Saransh-cpp. 🙏🏽

**Comment by jakirkham** [comment]
We have the beginnings of a `pyproject.toml` with PR ( https://github.com/zarr-developers/numcodecs/pull/369 ). Though more work in this area would be welcome 🙂

cc @DimitriPapadopoulos (in case this is of interest as well)

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/zarr-developers/numcodecs/pull/382 ), which moves as much as we can to `pyproject.toml`. Not sure if there is anything else we can move (though feedback on that would be welcome). Also am familiarizing myself with the process so may well have missed things that others will catch.

**Comment by jakirkham** [comment]
There may be small follow up things that come up. Would suggest raising them in new issues. Thanks all! 🙏
