### ISSUE TITLE
python 3.11 build needs removal of cython generated code

### ISSUE THREAD

**Issue by graziano-giuliani** [zarr-developers/numcodecs#367]
Package does not build under python 3.11. The cython generated c source files must be removed and cython added to dependency list for build. Builds successfully with python3.11 by removing:

numcodecs/_shuffle.c
numcodecs/blosc.c
numcodecs/compat_ext.c
numcodecs/lz4.c
numcodecs/vlen.c
numcodecs/zstd.c

and having cython installed. Note that Fedora has already as a policy that packages MUST NOT use files pre-generated by Cython:

https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_using_cython

**Comment by martindurant** [comment]
Out of interest, is there doc in cython alluding to this? The recommendation for a long time had been to yes, include generated C files in distributions.

**Comment by jakirkham** [comment]
In theory it just needs to be regenerated with a newer Cython

That being said, tend to agree with the sentiment of just dropping the vendored C. It has gotten to be a headache from a maintenance standpoint

IIUC the main reason to vendor C code before was build dependencies were difficult to specify and things like `setup_requires` has quirks. With `pyproject.toml`, this should be less of an issue, but we need to make the move first ( https://github.com/zarr-developers/numcodecs/issues/364 )

If anyone is interested in addressing issue ( https://github.com/zarr-developers/numcodecs/issues/364 ), that would be welcome 🙂

**Comment by jakirkham** [comment]
Agreed. Hence all the prebuilt binaries we ship (to hopefully avoid debugging users' compiler setups). Not to say the latter never happens though 😉

**Comment by jakirkham** [comment]
Python 3.11 was added and the generated C code removed with PR ( https://github.com/zarr-developers/numcodecs/pull/369 ). Should be available in the next release
