### ISSUE TITLE
Wheels for python 3.11 / Windows 11

### ISSUE THREAD

**Issue by schmidtnz** [zarr-developers/numcodecs#378]
Hi Team,
Trying to upgrade my project to python 3.11 and your package is one of the ones that is currently holding me back. 
I have put some effort into trying to build form source but not yet succeeded.
Would you be able to push wheels for python 3.11 please?
Stack trace was too long to include in post, has been attached here: [numcodecs.txt](https://github.com/zarr-developers/numcodecs/files/9914343/numcodecs.txt)
Many thanks in advance

**Comment by jakirkham** [comment]
Closing as this will be part of the next release ( https://github.com/zarr-developers/numcodecs/issues/377 )
