### ISSUE TITLE
`is_ndarray_like` has significant call overhead

### ISSUE THREAD

**Issue by ap--** [zarr-developers/numcodecs#379]
#### Problem description

Hello everyone,

I'm currently experimenting with decoding Aperio svs images via zarr directly to GPU. For that I tried to implement a [nvjpeg2k numcodecs-compatible](https://github.com/ap--/nvjpeg2k-numcodecs) decoder to decode directly to cupy ndarrays.

When profiling I noticed that a significant amount of time is spent on isinstance checks in `is_ndarray_like`. It seems that in the python typing module the Protocol meta-class generates the protocol attributes on every isinstance call instead of caching them.

In the profiling report below, you'll see that of the 77.3 seconds spent in `_chunk_getitem` 14.9 seconds are spent on `is_ndarray_like` (the bright pink block).

![Screenshot 2022-11-02 at 17 30 00](https://user-images.githubusercontent.com/1463443/199548689-e8240e89-46ee-44a4-8e7c-1972e64a2356.png)

I'll open a draft PR with a potential fix for discussion right away.

Cheers,
Andreas :smiley:

#### Version and installation information

Please provide the following:

* `numcodecs.__version__ == 0.10.2`
* Version of Python: 3.10.6
* Operating system: Linux
* Installed via conda

**Comment by ap--** [comment]
Closed via #380 

In my benchmark total accumulated runtime of `is_ndarray_like` reduced from 14.9 to ~0.6 seconds.

**Comment by jakirkham** [comment]
Thanks Andreas! 🎉

**Comment by joshmoore** [comment]
🤯
