### ISSUE TITLE
Drop Python 3.7?

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#381]
In Zarr PR ( https://github.com/zarr-developers/zarr-python/pull/1067 ), we dropped Python 3.7. Wondering if we should do the same here. Not aware of any pain it is causing us. So we could hang onto it a bit longer if we like. Though it is worth noting that [conda-forge has already dropped Python 3.7 builds]( https://conda-forge.org/docs/user/announcements.html#dropping-python-3-7 ).

**Comment by martindurant** [comment]
Is numpy still making wheels for 3.7?

**Comment by joshmoore** [comment]
Doesn't look like it: https://pypi.org/project/numpy/#files

**Comment by jakirkham** [comment]
Yeah they [dropped Python 3.7 in NumPy 1.22.0]( https://numpy.org/doc/stable/release/1.22.0-notes.html ).

That said, our usage of NumPy in Numcodecs is pretty simple (creating arrays, reshaping arrays, type conversion, etc.). So fairly old versions of NumPy work ok here.

**Comment by jakirkham** [comment]
Submitting PR ( https://github.com/zarr-developers/numcodecs/pull/405 ) to drop Python 3.7

**Comment by jakirkham** [comment]
FWIW here are [the PyPI stats]( https://pypistats.org/packages/numcodecs ).

Most downloads are Python 3.8 and newer. In particular Python 3.8 sees plenty of downloads generally.

Python 3.7 downloads are mostly low. Though there are a few unexplained spikes, which clamp down rather quickly.
