### ISSUE TITLE
Python 3.11 support?

### ISSUE THREAD

**Issue by hoodmane** [zarr-developers/numcodecs#397]
It would be nice to have a release with Python 3.11 support.

**Comment by joshmoore** [comment]
:+1: See the linked issues from coincidentally named 0.11 release: https://github.com/zarr-developers/numcodecs/issues/377

**Comment by jakirkham** [comment]
Closing to consolidate

**Comment by hoodmane** [comment]
Thanks! Github could really use a "closed in favor of (link to other issue)" option...
