### ISSUE TITLE
Investigate workflow reuse/refactoring

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#399]
> Barring that this feels like a candidate for refactoring (_a la_ https://docs.github.com/en/actions/using-workflows/reusing-workflows) :+1: for unification.

_Originally posted by @joshmoore in https://github.com/zarr-developers/numcodecs/pull/398#pullrequestreview-1180691357_

**Comment by dstansby** [comment]
This can probably be closed now https://github.com/zarr-developers/numcodecs/pull/532 is merged?
