### ISSUE TITLE
Release entry GH Action failing

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#401]
Seeing the following error from the [GH Action run]( https://github.com/zarr-developers/numcodecs/actions/runs/3474245896 ):

> [Invalid workflow file: .github/workflows/needs-release-notes.yaml#L2](https://github.com/zarr-developers/numcodecs/actions/runs/3474245896/workflow)
> `You have an error in your yaml syntax on line 2`

cc @Saransh-cpp

**Comment by jakirkham** [comment]
Was just an indentation issue. Fixed in the commit linked above and tested on PR to confirm ( https://github.com/zarr-developers/numcodecs/pull/366 ) it works

**Comment by Saransh-cpp** [comment]
Oops, my bad, should've tested this out before pushing.

**Comment by jakirkham** [comment]
All good. Once zarr-python worked, it was just a matter of comparing the two for differences (and then fixing them up)
