### ISSUE TITLE
Fletcher checksum codec

### ISSUE THREAD

**Issue by rabernat** [zarr-developers/numcodecs#410]
It would be great if numcodecs could implement the [Fletcher checksum](https://en.wikipedia.org/wiki/Fletcher%27s_checksum) algorithm in a way compatible with how hdf5 does it. In this version, the checksum is simply appended to the end of the chunk bytes. See https://github.com/fsspec/kerchunk/pull/274 for a dummy passthrough version.

There are some python implementations here:
- https://github.com/njaladan/hashpy/blob/master/hashpy/fletcherNbit.py
- https://gist.github.com/globby/9337839
- https://gist.github.com/AJPoulter-Soton/9d0d2505af64f0719bdee59b9a4533ba

**Comment by martindurant** [comment]
Some (fast) C implementations mentioned in https://stackoverflow.com/questions/40270450/correctness-of-fletcher32-checksum-algorithm (would cython well)

**Comment by rabernat** [comment]
And just for completeness, here is the hdf5 version as vendored by netcdf4:

https://github.com/Unidata/netcdf-c/blob/8eb71290eb9360dcfd4955ba94759ba8d02c40a9/plugins/H5checksum.c
