### ISSUE TITLE
Pip installation fails with the below error

### ISSUE THREAD

**Issue by bofinbabu** [zarr-developers/numcodecs#421]
```
  ERROR: Failed building wheel for numcodecs
Failed to build numcodecs
ERROR: Could not build wheels for numcodecs, which is required to install pyproject.toml-based projects
```
Python 3.10.4
OS 13.2.1 on M1 Pro

**Comment by joshmoore** [comment]
see: #289 #315 #342

You can use conda as a workaround for the moment.

**Comment by dstansby** [comment]
Is this still an issue with the latest version of numcodecs?

**Comment by dstansby** [comment]
Since arm64 wheels are now released for macOS I'll close this. Thanks for opening, and if you come across any more problems please do open more issues 😃
