### ISSUE TITLE
XOR delta

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/numcodecs#43]
Implement an XOR delta filter (XOR with previous value)

**Comment by ehgus** [comment]
I think it is solved by #595 .

**Comment by jakirkham** [comment]
Think the previous implementation of the `Delta` codec was using `np.diff`, which behaved similarly

Though yes it seems this works already with the `Delta` codec ( and is tested in https://github.com/zarr-developers/numcodecs/pull/595)

Closing as resolved
