### ISSUE TITLE
2 tests fail on `=numcodecs-0.11.0` with `ValueError: setting an array element with a sequence.`

### ISSUE THREAD

**Issue by TheChymera** [zarr-developers/numcodecs#436]
This is the full build log → https://ppb.chymera.eu/4bb4e7.log

Any ideas what's going on?

**Comment by QuLogic** [comment]
Looks like #333?

**Comment by TheChymera** [comment]
Seems to no longer be an issue as of `=numcodecs-0.12.1`.
