### ISSUE TITLE
Release v0.12.0

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#437]
Suggesting we do another release. Could do an alpha if we wanted, but that doesn't seem necessary.

Here's [the changes]( https://github.com/zarr-developers/numcodecs/compare/v0.11.0...main )

Thoughts?

**Comment by martindurant** [comment]
I support a release

**Comment by joshmoore** [comment]
Shall we roll out 0.12.0 and 2.15.0 together, @jakirkham?

**Comment by jsolbrig** [comment]
Will 0.12.0 be released sometime soon? I'm really anticipating #428 being released.

**Comment by jakirkham** [comment]
There was a bug encountered with NumPy 1.26+, which would be good to fix: https://github.com/zarr-developers/numcodecs/issues/470

Given Python 3.12 is out, we might want to add that to CI (wouldn't expect other changes needed)

IDK if we want to wait to release for these things or release and then re-release whenever those fixes land

**Comment by joshmoore** [comment]
I'd tend to get a release out ASAP (or ASAJIH -- "as soon as John is happy") and then roll another.

**Comment by jakirkham** [comment]
On further investigation, looks like the NumPy issue was an issue resolved in `main`. So a release will fix that problem (more reason to get a release out)

In terms of Python 3.12, things largely worked, but had to fix an entrypoint test issue: https://github.com/zarr-developers/numcodecs/pull/471

Side note: Think it is time for us to drop Python 3.8. If we would rather have a release with Python 3.8 first, then drop Python 3.8 right after, that is fine. That is, as long as CI remains cooperative (there were some issues cropping up recently with Python 3.8 builds in the Python 3.12 PR). Though would also be ok just dropping it in the Python 3.12 PR (as part of this release)

**Comment by jakirkham** [comment]
Went ahead and merged PR: https://github.com/zarr-developers/numcodecs/pull/471

Going to kick off the release

**Comment by jakirkham** [comment]
Have tagged the release here: https://github.com/zarr-developers/numcodecs/releases/tag/v0.12.0

**Comment by jakirkham** [comment]
Seeing some sporadic issues with macOS CI where it tries to use AVX2 instructions. We might want to just turn this off completely. Doubt CI has hardware to cover this instruction. Though unsure why this issue is coming up now

Tracking in issue: https://github.com/zarr-developers/numcodecs/issues/473

**Comment by jakirkham** [comment]
Now available on PyPI & conda-forge! 🚀 

Closing...

**Comment by jakirkham** [comment]
As noted elsewhere, there were a couple bugs that surfaced recently. Most notably issue ( https://github.com/zarr-developers/numcodecs/issues/478 ). Fixes for these are now in

Have cut 0.12.1. Wheels are already up. Conda-forge packages are in progress: https://github.com/conda-forge/numcodecs-feedstock/pull/101

**Comment by rabernat** [comment]
Thanks for your work @jakirkham! Appreciate it! 🙏

**Comment by jakirkham** [comment]
Packages are up on conda-forge. Just waiting for them to mirror to CDN. Typically that takes ~15mins after upload (though could be longer)
