### ISSUE TITLE
Fletcher32 does not inherit from Checksum32

### ISSUE THREAD

**Issue by mkitti** [zarr-developers/numcodecs#447]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```python
In [1]: import numcodecs

In [7]: issubclass(numcodecs.Fletcher32, numcodecs.abc.Codec)
Out[7]: True

In [8]: issubclass(numcodecs.Fletcher32, numcodecs.checksum32.Checksum32)
Out[8]: False

```

#### Problem description

`Fletcher32` is a 32-bit checksum, but it is not a subclass of Checksum32

Should it be? Also does this affect the documentation?

**Comment by martindurant** [comment]
I am not aware of any technical use case in which the class hierarchy would matter. No methods would be inherited from Checksum32. The only reason could be, as you say, to indicate membership of a group for documentation.

**Comment by mkitti** [comment]
I suppose this is not a problem as long as the Fletcher32 is documented along with the other 32-bit checksums.
