### ISSUE TITLE
Local doc build claims sphinx not installed, when it is

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/numcodecs#457]
#### Minimal, reproducible code sample, a copy-pastable example if possible

```bash
cd docs
make html
```

#### Problem description
Running the above code I get:
```
Makefile:12: *** The 'sphinx-build' command was not found. Make sure you have Sphinx installed, then set the SPHINXBUILD environment variable to point to the full path of the 'sphinx-build' executable. Alternatively you can add the directory with the executable to your PATH. If you don\'t have Sphinx installed, grab it from http://sphinx-doc.org/.  Stop.
```
But I have sphinx installed!
```
> which sphinx-build
/Users/dstansby/mambaforge/envs/numcodecs/bin/sphinx-build
```

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__``: current main branch
* Version of Python interpreter: 3.11
* Operating system (Linux/Windows/Mac): Mac
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda"): 

Also, if you think it might be relevant, please provide the output from ``pip list`` or
``conda list`` depending on which was used to install NumCodecs.

**Comment by QuLogic** [comment]
The check added in #451 is not portable; see e.g., https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then
