### ISSUE TITLE
Sporadic AVX2 failures on macOS CI

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#473]
Have recently started seeing issues where macOS CI builds try to use AVX2 instructions even though they are likely unavailable on CI. However this is sporadic as it doesn't always occur in the same builds or Python versions. Rerunning CI seems to sometimes fix the issue. Maybe we just need to disable AVX2 in CI to fix this.

**Comment by jakirkham** [comment]
Think this is related to this change: https://github.com/zarr-developers/numcodecs/pull/428

Looking at the config, think the `DISABLE_NUMCODECS_AVX2` environment variable is getting overridden in the macOS case. Guessing we either need to include that explicitly in the macOS case or configure the macOS case to extend (and not override) flags generally set

https://github.com/zarr-developers/numcodecs/blob/680d0205ab9e32440c4c1d5f3601fd9fbfdf6bf1/pyproject.toml#L115-L121

**Comment by jakirkham** [comment]
cc @psobolewskiPhD (in case you have ideas here)

**Comment by psobolewskiPhD** [comment]
I understood that `tool.cibuildwheel` applied globally, but maybe not... 
...and maybe not all runners have AVX2, hence the issue?
I'll make a PR to add `DISABLE_NUMCODECS_AVX2=1` under `tool.cibuildwheel.macos`...

**Comment by jakirkham** [comment]
FWIW am not certain either. Though that seemed like a plausible working theory that explained the behavior so far

Sounds good. Thanks Peter! 🙏

We can give that a try and see how things go 🙂

**Comment by jakirkham** [comment]
Reopening as this issue is coming up in recent wheel builds: https://github.com/zarr-developers/numcodecs/pull/474#issuecomment-1765442101

**Comment by jakirkham** [comment]
Looking at these errors, it appears to be macOS ARM that is failing. So maybe the override needs this option too
