### ISSUE TITLE
Add wheels for Python 3.12

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/numcodecs#480]
Now Python 3.12 is released, it would be good to publish wheels for it.

**Comment by jakirkham** [comment]
Agreed. Especially since the code is now tested on Python 3.12

Is this something you would be interested in working on David?

Should just be a matter of updating [`cibuildwheel` in GHA]( https://github.com/zarr-developers/numcodecs/blob/main/.github/workflows/wheel.yaml )

**Comment by dstansby** [comment]
I don't think anything needs updating, as it builds all wheels by default. On https://github.com/zarr-developers/numcodecs/pull/474 the Python 3.12 wheels are built, so I think it just requires someone who can upload to PyPI to build the wheels for the last tagged release and upload them.

**Comment by jakirkham** [comment]
The wheel uploads are automatic and we just did a release. What else are we still missing?

**Comment by dstansby** [comment]
It looks like 0.12.0 was built using cibuildwheel 2.14 (https://github.com/zarr-developers/numcodecs/actions/runs/6435028120/job/17476132676), but cibuildwheel needs to be 2.16.1 to build Python 3.12 wheels (https://github.com/pypa/cibuildwheel/releases/tag/v2.16.2), so the answer seems to be fix/merge this PR: https://github.com/zarr-developers/numcodecs/pull/474

**Comment by jakirkham** [comment]
Ok if you have time/interest to look into fixing that PR, your assistance would be greatly appreciated 🙂

**Comment by jakirkham** [comment]
PR ( https://github.com/zarr-developers/numcodecs/pull/474 ) is now merged

What else is still needed here?

**Comment by jakirkham** [comment]
We just released 0.12.1. It appears it uploaded wheels for Python 3.12. So looks like this is done. Closing...

<img width="1840" alt="Screenshot 2023-10-17 at 5 49 23 PM" src="https://github.com/zarr-developers/numcodecs/assets/3019665/59cf5086-77f0-4e57-a80a-7861dcb4480d">
