### ISSUE TITLE
Is Snappy algorithm available with Blosc?

### ISSUE THREAD

**Issue by paumillet** [zarr-developers/numcodecs#495]
Hello there,

I was just wondering if Snappy algorithm was available again with Blosc compressor?

From what I've read, it was temporarily unavailable because of c-blosc upgrade in version 0.9.0.
But it's currently written in last version (numcodecs 0.12.1) [docs of Blosc](https://numcodecs.readthedocs.io/en/stable/blosc.html#numcodecs.blosc.Blosc) that `cname` parameter is:
> A string naming one of the compression algorithms available within blosc, e.g., ‘zstd’, ‘blosclz’, ‘lz4’, ‘lz4hc’, ‘zlib’ or **‘snappy’**

Also, it seems like Snappy is made available with last versions of [c-blosc](https://github.com/Blosc/c-blosc).

Despite all this, I can't find Snappy algorithm in the list provided by 
```python
numcodecs.blosc.list_compressors()

['blosclz', 'lz4', 'lz4hc', 'zlib', 'zstd']
```
Is there a problem with my installation or is Snappy not available? If so, when will it be available again?

* Value of ``numcodecs.__version__`` : `'0.12.1'`
* Version of Python interpreter:  `Python 3.9.16`
* Operating system (Linux/Windows/Mac): Linux
* How NumCodecs was installed : using pip into virtual environment

Thanks in advance for your answer!

**Comment by mkitti** [comment]
snappy is not currently included in https://github.com/Blosc/c-blosc/tree/main/internal-complibs which is where numcodecs would normally obtain the compression libs from.

**Comment by paumillet** [comment]
Ok, thanks for your reply!
