### ISSUE TITLE
Release 0.12.2?

### ISSUE THREAD

**Issue by mwlon** [zarr-developers/numcodecs#525]
I've noticed that the last release was ~7 months ago, and pcodec support was added 3 months ago. Should a new version be released?

**Comment by rabernat** [comment]
Thanks for the ping @mwlon! Yes we should make a release.

**Comment by jakirkham** [comment]
Basically would make sure the release notes are up-to-date for the release we are making. Like updating [these lines]( https://github.com/zarr-developers/numcodecs/compare/v0.12.1...main#diff-c1601e04e71984130945f082e2e4393fc5fae9a86f35ea942a36b576e6f5f7ceR9-R12 ) with the version

Then we can just [create a new release on GitHub]( https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

**Comment by normanrz** [comment]
@dstansby Could you add a PR that adds the new Python support policy #531 to the readme and docs?

**Comment by mwlon** [comment]
FYI I'll release a new version of pcodec with some format additions within the next week, so it might be advantageous to wait for that and upgrade to the pcodec 0.2 pip package.

**Comment by mwlon** [comment]
The 0.2.0 pip package is out now

**Comment by rabernat** [comment]
v0.13.0 is on pypi: https://pypi.org/project/numcodecs/0.13.0/ 😅 

I followed the [release procedure](https://numcodecs.readthedocs.io/en/stable/contributing.html#release-procedure) and it seemed to work fine.

The one thing I did not do was create an actual release on https://github.com/zarr-developers/numcodecs/releases
Is that a manual step?

Readthedocs does not seem to have picked up on the release and has not added a 0.13.0 version or updated stable: https://readthedocs.org/projects/numcodecs/versions/

**Comment by mwlon** [comment]
Looks like the documentation needs an update? https://numcodecs.readthedocs.io/en/stable/release.html

**Comment by rabernat** [comment]
Correct, but I personally don't know how to make it update. I thought RTD would automatically detect a new tag, but that hasn't happened. We probably need help from @jakirkham.

**Comment by rabernat** [comment]
Looks like RTD has finally updated. Not sure why it was so delayed. I added the release at https://github.com/zarr-developers/numcodecs/releases, I I guess we can say 0.13.0 is officially out!

@mwlon I'm planning to make a short blog post about pcodec in Zarr in the next few weeks. I'd love to get your feedback on that before publishing.

**Comment by mwlon** [comment]
@rabernat sounds good, happy to give feedback when you have a draft
