### ISSUE TITLE
classmethod properties are removed in Python 3.13

### ISSUE THREAD

**Issue by QuLogic** [zarr-developers/numcodecs#553]
#### Problem description

This was added in #519:
https://github.com/zarr-developers/numcodecs/blob/696e58253494f4ffb21f4d3ca30e298b22c1c929/numcodecs/zstd.pyx#L261-L277

However, as of Python 3.11, using `classmethod` on `property` was deprecated, and has been removed in Python 3.13:
https://docs.python.org/3.13/library/functions.html#classmethod
> Deprecated since version 3.11, removed in version 3.13: Class methods can no longer wrap other [descriptors](https://docs.python.org/3.13/glossary.html#term-descriptor) such as [property()](https://docs.python.org/3.13/library/functions.html#property).

This causes tests to fail on Python 3.13:
```
____________________________ test_native_functions _____________________________
    def test_native_functions():
        # Note, these assertions might need to be changed for new versions of zstd
>       assert Zstd.default_level == 3
E       AssertionError: assert <bound method default_level of <class 'numcodecs.zstd.Zstd'>> == 3
E        +  where <bound method default_level of <class 'numcodecs.zstd.Zstd'>> = Zstd.default_level
../../BUILDROOT/usr/lib64/python3.13/site-packages/numcodecs/tests/test_zstd.py:93: AssertionError
```
https://kojipkgs.fedoraproject.org/work/tasks/9111/120819111/build.log

#### Version and installation information

Please provide the following:

* Value of ``numcodecs.__version__`` 0.13.0
* Version of Python interpreter 3.13.0b3
* Operating system (Linux/Windows/Mac) Fedora Rawhide
* How NumCodecs was installed (e.g., "using pip into virtual environment", or "using conda") from source

**Comment by QuLogic** [comment]
Ping? We're less than a month away from Python 3.13 final.

**Comment by dstansby** [comment]
I guess a blocker to this is running tests on Python 3.13. Do you know the best way to test on pre-release Python these days? We're currently using conda to manage Python in the tests, which last time I checked didn't ship pre-release versions of Python, but I'm open to moving to another way of managing Python in CI if it gives us pre-release Python.

**Comment by QuLogic** [comment]
For Matplotlib, we use `actions/setup-python@v5` with `allow-prereleases: true` and the usual `pip` install. I don't know about all `numcodecs` dependencies though.
