### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by juntyr** [zarr-developers/numcodecs#564]
Thank you for working on this package - it has been invaluable in my research work!

I have been working on some Rust bindings for numcodecs (https://github.com/juntyr/numcodecs-rs) which have just hit their first release. The bindings contain (1) one base crate, numcodecs, which provides a Rusty version of the numcodecs API, and (2) the numcodecs-python crate, which allows Python codecs to be used in Rust and Rust codecs to be used in Python.

There are also some other bits and pieces which are more related to my ongoing research.

I hope these bindings prove helpful to the community!

**Comment by MSanKeys963** [comment]
That's great, @juntyr! 
Thanks for using the library and working on Rust bindings. It'd prove useful to the broader Zarr community.

Would you mind if I did a quick shoutout across Zarr's social channels?

**Comment by juntyr** [comment]
> It'd prove useful to the broader Zarr community.

I’m really glad to hear that!

> Would you mind if I did a quick shoutout across Zarr's social channels?

Absolutely, thanks!

**Comment by dstansby** [comment]
Thanks for letting us know! I think we can close this issue since it doesn't need any more action - please do feel free to open other issues if there's anything else we can do to help though.
