### ISSUE TITLE
Add crc32c codec

### ISSUE THREAD

**Issue by dstansby** [zarr-developers/numcodecs#610]
There's a request to add `crc32c` as a codec here, so `zarr-python` v3 can use it for sharding. I'm not entirely sure on the details, so someone more familiar might want to add a more in depth comment about this. More context at https://github.com/zarr-developers/zarr-python/issues/2391

**Comment by normanrz** [comment]
Would we just declare `crc32c` as a dep here or compile the code within numcodecs?

**Comment by dstansby** [comment]
I'm pro adding it as a dependncy (and adding a corresponding `Codec` class for it)

**Comment by normanrz** [comment]
Should the codec append a checksum, as it does in zarr-python right now, or just compute the checksum (hard to decode, though)?
