### ISSUE TITLE
Coverage off in `test_zarr3.py`

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#636]
It looks like `test_zarr3.py` is falling below coverage. Not sure what is expected to be covered or not here. So flagging it in an issue

https://app.codecov.io/gh/zarr-developers/numcodecs/blob/main/numcodecs%2Ftests%2Ftest_zarr3.py

**Comment by dstansby** [comment]
These lines should be fixed by https://github.com/zarr-developers/numcodecs/pull/633.
