### ISSUE TITLE
get_codec modifies its argument 

### ISSUE THREAD

**Issue by jeromekelleher** [zarr-developers/numcodecs#78]
The ``get_codec`` function modifies its argument, popping the "id" key. This can lead to surprising behaviour such as:

```python
config = {"id": "json"}
codec = get_codec(config) # Works
codec = get_codec(config) # fails.
```

I suggest adding ``config = dict(config) `` at the start of the function. The performance implications should be minimal I think.

**Comment by alimanfoo** [comment]
SGTM, although I think there may be some other code that relies on the "id" having been popped. May need some adjustment. PR welcome.
