### ISSUE TITLE
Regenerate cythonized C sources for Python 3.7 compatibility

### ISSUE THREAD

**Issue by alimanfoo** [zarr-developers/numcodecs#86]
To enable building of the C extensions on Windows under Python 3.7, the C sources need to be regenerated with a recent version of cython.

**Comment by jakirkham** [comment]
As clarification, recent means at least Cython 0.27.3.

ref: https://github.com/zarr-developers/zarr/pull/308#issuecomment-431127112

**Comment by jakirkham** [comment]
Addressing in PR ( https://github.com/zarr-developers/numcodecs/pull/90 ).
