### ISSUE TITLE
Refresh Requirements

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#91]
The requirements (particularly in `requirements_dev.txt`) are lagging a bit. Would be good to update them as was done with Zarr not too long ago.

xref: https://github.com/zarr-developers/numcodecs/pull/90#issuecomment-434828986

**Comment by alimanfoo** [comment]
FWIW on reflection I'm in favour of removing all but direct dependencies from requirements files and using PyUP bot to manage requirements files.

**Comment by jakirkham** [comment]
Sure. SGTM. We can at least try it and see how it goes if nothing else.

Would probably be worth adding a `pip freeze` line to the CIs. That way we can inspect dependency changes around times when issues emerge.

**Comment by alimanfoo** [comment]
#94 has been merged, this is resolved.
