### ISSUE TITLE
Support timeline for Windows 32-bit

### ISSUE THREAD

**Issue by jakirkham** [zarr-developers/numcodecs#97]
Raising to see how long we want to support Windows 32-bit and if there are particular needs motivating its support. Asking as this effectively doubles our CI time. So want to make sure that is an allocation that we are comfortable with.

FWIW in conda-forge we did a poll earlier this year to see how many Windows 32-bit users we have and whether it made sense to support the platform further. We learned a [very small percentage of users are on Windows 32-bit with most on 64-bit]( https://gitter.im/conda-forge/conda-forge.github.io?at=5ace39431130fe3d36c7da37 ). It goes without saying that we opted to drop Windows 32-bit after learning this.

**Comment by alimanfoo** [comment]
I'd support dropping 32-bit, especially if conda-forge has dropped it.
Speeding up CI would really benefit the development process.

**Comment by jakirkham** [comment]
As to speeding up CI, enabling fast-finish for builds should also help. ( https://github.com/zarr-developers/numcodecs/issues/123 )

**Comment by alimanfoo** [comment]
I'll drop 32-bit support in the next release (whatever comes after 0.6.1) unless anyone objects.

**Comment by jakirkham** [comment]
Dropping 32-bit is probably for the best.
